# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fdf476b7b3bb1e07919a0211536c3713d76d003b255d604929ad3bb5302eb4d740d88edc7a3b3c63581b43db79f16b6d63bd98db38965a8de114e74e06c0ba9

test:
  secret_key_base: 2ccc60dd75d5eff537840312b4b2f4f520067e4d305b028b5734f7451a609595eafba79914c4994a9eceb4096963333a3a5607e4a61bbde8601f84b9ee64327e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
